### ISSUE TITLE
limit osi współrzędnych

### ISSUE THREAD

**Issue by Janek003** [MRKosmitapL/position-vector-function-plotter#1]
```
ax.set_xlim(0, step * max(eval(czastka.A, {'t': points_limit}) for czastka in czastki))
ax.set_ylim(0, step * max(eval(czastka.B, {'t': points_limit}) for czastka in czastki))
```
jeśli A byłoby równe (-t) to max A byłoby = 0, i dobrze by było gdyby dolny i górny limit był wyznaczany, nie wiem czy jest to warte zachodu

**Comment by MRKosmitapL** [comment]
nie chcę już dodawać kolejnych inputów bo i tak jest ich już dużo, co ciekawe faktycznie powinno być max = 0 przy podaniu ujemnego "t". Z jakiegoś powodu jednak tak nie jest i nadal podaje "największą liczbę" tylko z znakiem ujemnym

**Comment by Janek003** [comment]
> nie chcę już dodawać kolejnych inputów bo i tak jest ich już dużo, co ciekawe faktycznie powinno być max = 0 przy podaniu ujemnego "t". Z jakiegoś powodu jednak tak nie jest i nadal podaje "największą liczbę" tylko z znakiem ujemnym

nie wiedziałem że max() takie rzeczy robi, ja dla ćwiczenia zrobię te limity dolne i górne bo zwłaszcza w przypadku gdy np
r1 = -t * i + -t * j
r2 = t * i + t * j
to dobrze by było dla np: t = 4, żeby było od -4 do 4 x i y osie

**Comment by Janek003** [comment]
```
t = max_t

x_skrajnosci = [0]
y_skrajnosci = [0]

for j in range(line_num):
    x_skrajnosci.append(eval(a_list[j]))
    y_skrajnosci.append(eval(b_list[j]))

x_min = min(x_skrajnosci)
x_max = max(x_skrajnosci)

y_min = min(y_skrajnosci)
y_max = max(y_skrajnosci)


fig = plt.figure()
axis = plt.axes(xlim = (x_min, x_max), ylim = (y_min, y_max)) 
```
